AAkira/Kotlin-Multiplatform-Libraries

README.md

Version 0.3+ now includes more platforms.
Tried to change [badge-native] to [badge-ios] but it doesn't appear to render, so I left that alone.

Add mac, js, and jvm platforms for Multiplatform Settings

---

README.md

Probably useful for those that want to expose suspending functions to iOS & co

add kotlin-native-suspend-function-callback

---

README.md

- Generates strict types from GraphQL operations
- Isolate GraphQL from business logic by composable links
Link to docs
https://kmpdocs.suparnatural.com/graphql/

suparnatural-graphql: Strict Type Safe GraphQL client

---

README.md

Port of [ReKotlin](https://github.com/ReKotlin/ReKotlin) to Kotlin Multiplatform, which corresponds to [ReKotlin/1.0.4](https://github.com/ReKotlin/ReKotlin/releases/tag/1.0.4). Supports **JVM**, **Android**, **iOS**.
Useful links:
- GitHub repo: https://github.com/xorum-io/ReKamp
- Bintray repo: https://bintray.com/beta/#/xorum-io/ReKamp/ReKamp
- Example of usage: https://github.com/xorum-io/codeforces_watcher/blob/dev/common/build.gradle

Add ReKamp.

---

README.md

- Kodein-DB is a new K/M library that provide.a NoSQL embedded database for iOS and Android.
- fix naming of DI lib to *Kodein-DI*.

add Kodein-DB

---

README.md

This library contains a few monads that I found very useful in Scala, and that I couldn't cope without in Kotlin: `Option`, `Try` and `Either`.
It's a port of Scala sources to Kotlin Multiplatform with Kotlin naming conventions and some additional extension functions.
Links:
* [Library page](https://czerwinski.it/projects/kotlin-util/)
* [Library sources](https://github.com/sczerwinski/kotlin-util)

Add Kotlin utilities library

---

README.md

I've created this library https://github.com/Chozzle/compose-macos-theme
It could be very useful for anyone wanting to write a Multiplatform app UI, that appears native.

Add compose-macos-theme

---

README.md

[Muirwik](https://github.com/cfnz/muirwik) is a material-ui wrapper written in Kotlin similar to kotlin-material-ui. Both seem to be similar in popularity and therefore should both be here.

Add Muirwik

---

README.md

Adds the [connectivity status](https://github.com/ln-12/multiplatform-connectivity-status) library. It is a helpful utility if you want to monitor the device connection state.

Adding connectivity status

---

README.md

https://github.com/JuulLabs/kable/pull/64 added support for iOS to the Kable library.
_Draft until release is published._

Add iOS badge to Kable

---

README.md

According to the docs Ktor does support the 3 desktop platform
https://ktor.io/docs/http-client-multiplatform.html#posix-compatible-desktops-macos-linux-windows

Add linux, windows and macOS badge to Ktor

---

README.md

The current link leads to 404.

Fixes link to GraphQL apollo client

---

README.md

kotlin-multiplatform-diff - https://github.com/petertrr/kotlin-multiplatform-diff - is based on [java-diff-utils](https://github.com/java-diff-utils/java-diff-utils), rewritten in Kotlin with multiplatform support.

Add kotlin-multiplatform-diff - a library for calculating text differences

---

README.md

[Decompose](https://github.com/arkivanov/Decompose) is a KMP version of the business logic component (BLOC) pattern with navigation functionality and is made from the same author of [MVIKotlin](https://github.com/arkivanov/MVIKotlin). There is a [sample](https://github.com/JetBrains/compose-jb/tree/master/examples/todoapp) in the Jetbrains compose repository that showcases its usage with testing. 
Also updated the targets for MVIKotlin since [watchOS support was added](https://github.com/arkivanov/MVIKotlin/issues/229).

add decompose to the architecture category and update MVIKotlin targets

---

README.md

Adds `component-encoding` library to `Utilities` section.
[Library Link](https://github.com/05nelsonm/component-encoding)
Because encoding is a must have in most any project :smile:

Add encoding library

---

README.md

Adds the `kmp-tor` library to the `Network.Http` section
[Library Link](https://github.com/05nelsonm/kmp-tor)
`kmp-tor` is a library for embedding Tor into an application for facilitating access to the Tor network.

Add `kmp-tor` library

---

README.md

[Mockative](https://github.com/mockative/mockative)
Mockative is a kotlin multiplatform testing library that can help create mocks for interfaces to be used from common tests.

add mockative to testing libraries

---

README.md

Adds the `multiplatform-viewmodel` library to the Architecture section
[Library Link](https://github.com/doublesymmetry/multiplatform-viewmodel)
`multiplatform-viewmodel` is a library providing a shared `ViewModel` to use in your presentation layer

Add `multiplatform-viewmodel` library

---

README.md

We've since added a lot more supported platforms.

Add more platforms for kotlin-result

---

README.md

* Type-safe time periods for the Kotlinx-datetime multiplatform date/time library
[Library Link](https://github.com/sebj/time)
---

Add sebj/time to README.md

---

README.md

* Résultat is a fork of Kotlin [Result](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-result/) with a loading state.
* [Library Link](https://github.com/nicolashaan/resultat)
---

Add Résultat library

---

README.md

* compose_bloc is a state management and navigation library for compose multiplatform
[compose_bloc](https://github.com/beyondeye/compose_bloc)
---
- [ x ] Confirmed that two spaces were added at the end of the description to break a new line.

added link to compose_bloc:

---

README.md

* This is a kotlin multiplatform runtime [infix](https://en.wikipedia.org/wiki/Infix_notation) expressions evaluator.
[Library Link](https://github.com/murzagalin/multiplatform-expressions-evaluator)
---

Added expressions evaluator

---

README.md

* Library description (If you want to write)
The easiest HTTP networking library for Kotlin backed by Kotlinx Coroutines.
[Library Link](https://github.com/kittinunf/fuel)
---

New Network lib

---

README.md

- `parcelize`
- [REPOSITORY](https://github.com/05nelsonm/component-parcelize)
- Enables the implementing of `android.os.Parcelable` interface from `commonMain` source set
- `encoding`
- [REPOSITORY](https://github.com/05nelsonm/component-encoding)
- Updated entry:
- Description modification
- Added support badges
- Moved to section `Serialization`
- `value-clazz`
- [REPOSITORY](https://github.com/05nelsonm/component-value-clazz)
- Abstraction that is functionally equivalent to a Kotlin `value class` that implements an `interface`, but will compile to platform code (unlike Kotlin `value class`es such as `kotlin.Result`)
I also added a badge in there for `android-native` that is similar to the `support [AppleSilicon]` and `support [IR]` badges. Can remove if you object, hopefully not …

Add entries `parcelize`, `value-clazz` and update `encoding`

---

README.md

* simple, bidirectional eventbus library written in common multiplatform kotlin,it has some extra features like inspection/removing hook, mutex-locking for concurrent publish/add from current eventbus library stated in the list
[Event4k](https://github.com/nort3x/event4k)
---

add event4k library

---

README.md

Ktoml - MPP serialization library (decoder/encoder) for TOML format.
[Ktoml](https://github.com/akuleshov7/ktoml)
---

Adding Ktoml library

---

README.md

Swift Klib helps easily include your Swift source files in your KMM shared module and access them in Kotlin via cinterop for iOS targets. It is useful for:
* Accessing Swift-only libraries
* Creating a Kotlin-Friendly Swift API
* Learning how Swift <-> Kotlin interoperability works
[Library Link](https://github.com/ttypic/swift-klib-plugin)
---

Add Swift Klib gradle plugin

---

README.md

* Shared ViewModel in Kotlin Multiplatform - A Kotlin Multiplatform library that provides shared MVVM for UI applications. Components are lifecycle-aware on Android.
* Supports Android Parcelable, Kotlin Parcelize, AndroidX SavedStateHandle for restoring state after process death.
* The ViewModel class is a business logic or screen level state holder. It exposes state to the UI and encapsulates related business logic. Its principal advantage is that it caches state and persists it through configuration changes (on Android).
[Library Link](https://github.com/hoc081098/kmp-viewmodel)
---

Add `kmp-viewmodel`

---

README.md

* KStateMachine is a Kotlin DSL library for creating state machines and hierarchical state machines (statecharts).
[Library Link](https://github.com/nsk90/kstatemachine)
---

Add KStateMachine

---

README.md

* A declarative, Kotlin-idiomatic API for writing dynamic console applications.
[Kotter](https://github.com/varabyte/kotter)
---

Add Kotter CLI multiplatform library

---

README.md

* A Kotlin multiplatform unit testing library inspired by / similar to Google Truth.
[Truthish](https://github.com/varabyte/truthish)
---

Add Truthish multiplatform testing library

---

README.md

- `KotlinCrypto/hash`
- `KotlinCrypto/MACs`
- `KotlinCrypto/sponges`
- `KotlinCrypto/secure-random`
- `KotlinCrypto/endians`
All libs can be found under the [KotlinCrypto](https://github.com/KotlinCrypto) organization
---

Add `KotlinCrypto` libraries

---

README.md

The old link went to an archived repository, which contained this link. I figured this would make it simpler if the link went straight to the target

Update link to Korim

---

README.md

* Sentry SDK for Kotlin Multiplatform.
[sentry-kotlin-multiplatform](https://github.com/getsentry/sentry-kotlin-multiplatform)
---

Add sentry-kotlin-multiplatform SDK

---

README.md

[RSocket](https://rsocket.io) Kotlin multi-platform implementation based on [kotlinx.coroutines](https://github.com/Kotlin/kotlinx.coroutines) and [Ktor](https://github.com/ktorio/ktor).
[Library Link](https://github.com/rsocket/rsocket-kotlin)
Type-safe Multiplatform cryptography library for Kotlin.
The library doesn't implement any cryptography algorithm on its own, but wraps well-known future-proof solutions
like [OpenSSL 3.x](https://www.openssl.org), [WebCrypto](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) or [JCA](https://docs.oracle.com/en/java/javase/17/security/java-cryptography-architecture-jca-reference-guide.html) with type-safe multiplatform API providing uniform experience with aligned default behavior, and same expected results using identical parameters …

Add rsocket-kotlin and cryptography-kotlin

---

README.md

This library is a port of Adobe's XMP SDK to Kotlin Multiplatform.
https://github.com/Ashampoo/xmpcore
---

Add XMP Core

---

README.md

* A KMP wrapper for couchbase lite
---

Added Couchbase lite to list

---

README.md

* DrawBox is a multipurpose tool to draw anything on canvas, written completely on Compose Multiplatform. This is the first multiplatform drawing library!
[Library Link](https://github.com/MarkYav/DrawBox)
---

Add DrawBox

---

README.md

*   A Typing Animation Library for Compose Multiplatform
https://github.com/zeeshanali-k/typist-cmp
---
- [ Yes] Confirmed that two spaces were added at the end of the description to break a new line.

Added Typist-CMP

---

README.md

* RSS Parser is a Kotlin Multiplatform library for parsing RSS and Atom feeds. It supports Android, iOS, and the JVM.
* 
[Library Link](https://github.com/prof18/RSS-Parser)
--- 
I was not sure if it was fitting under the existing categories. So I created a "Parsing" subsection under "Utility". Let me know if it works for you or feel free to move it under a more appropriate section! 🙏 
---

Add RssParser

---

README.md

* *jsmints* is a suite of libraries and gradle plugins for working with Kotlin JS, with a focus on testing and version updating.
[Library Link](https://github.com/robertfmurdock/jsmints)
---
- [✅] Confirmed that two spaces were added at the end of the description to break a new line.

add jsmints

---

README.md

Adds KMP-ComposeUIViewController
KSP library for generating ComposeUIViewController and UIViewControllerRepresentable files when using Compose Multiplatform for iOS
[Library Link](https://github.com/GuilhE/KMP-ComposeUIViewController)
---

Adds KMP-ComposeUIViewController

---

README.md

Fix project name for jsonrpc-kotlin-client

---

README.md

* A small non-opinionated library to implement MVI with the state-machine pattern.
[CommonStateMachine](https://github.com/motorro/CommonStateMachine)
---

CommonStateMachine

---

README.md

* Kotlin Multiplatform library for Couchbase Lite—a lightweight, embedded, syncable, NoSQL database
[Library Link](https://github.com/jeffdgr8/kotbase)
---

Add Kotbase Couchbase Lite

---

README.md

* kotlinx-uuid is a multiplatform (MPP) [Kotlin](https://kotlinlang.org/) library introducing support for [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier).  
[kotlinx-uuid](https://github.com/hfhbd/kotlinx-uuid). 
---

add another common used kotlinx-uuid

---

README.md

* AWSS3 is an AWS extension for kmp as there is currently no library that does it.
[AWS KMP](https://github.com/estivensh4/aws-kmp)
---

add AWS library

---

README.md

* Kotlin Multiplatform library for Compose Multiplatform, designed for seamless integration of an image picker feature in iOS and Android applications.
* It has a multiple image picker feature + ability to select the maximum number of images for iOS and Android target.
[peekaboo](https://github.com/TEAM-PREAT/peekaboo)
---

Add peekaboo

---

README.md

ksoup library badges updated
* HTML & XML Parser
[Library Link](https://github.com/fleeksoft/ksoup)
---

ksoup library badges updated

---

README.md

A modern MAVLink library for Kotlin Multiplatform.
MAVLink is a very lightweight messaging protocol for communicating with drones (and between onboard drone components).
mavlink-kotlin was created out of the need for a type-safe, high-performance and flexible MAVLink library for targeting multiple platforms. Through mavlink-kotlin we want to address the problems that we had faced while adopting and understanding MAVLink libraries not only for the JVM but also C/C++, Golang, Rust and Python. This library takes inspiration from several great features of these libraries. We want to make the adoption of this library as easy as possible by being flexible in terms of creating a modular and easy-to-extend API that allows the users to use the same base MAVLink and connection classes to create …

Add mavlink-kotlin

---

README.md

Multiplatform Material 2 and Material 3 animated slider similar to the one introduced in Android 13 media player.
See the live, interactive Web version in [its website](https://mahozad.ir/wavy-slider).
[Library Link](https://github.com/mahozad/wavy-slider)
---

Add Wavy slider

---

README.md

* A multiplatform navigation library built for, and seamlessly integrated with, Jetpack Compose.
[Library Link](https://github.com/adrielcafe/voyager)
[Library Docs](https://voyager.adriel.cafe/)
---

Adding Voyager lib in the catalog

---

README.md

* A library that adds additional Kotlin/Multiplatform targets to AndroidX Paging, and provides UI components to use Paging on iOS. 
[Multiplatform Paging](https://github.com/cashapp/multiplatform-paging)
The old one is archived and I replaced it with another library which is recommended in the archived library.
---

Replace archived paging lib

---

README.md

Compose Multiplatform Navigation - Pragmatic, type safety navigation for Compose Multiplatform. Based on Freeletics Khonshu Navigation. ViewModel, SavedStateHandle, Lifecycle, Multi-Backstacks, Transitions, Back-press handling, and more...  
[Library Link](https://github.com/hoc081098/solivagant)
---

Add `solivagant` library

---

README.md

[Library Link](https://github.com/hoc081098/kmp-viewmodel)
Since https://github.com/hoc081098/kmp-viewmodel/releases/tag/0.7.0, `wasm` target and `nodejs` target have been supported
---

Update `kmp-viewmodel`: add `wasm`, `nodejs` target

---

README.md

* A Kotlin Multiplatform library to provide regular date-time functionality and interoperability needed with very minimal platform dependencies.  
[Library Link](https://github.com/sunny-chung/kdatetime-multiplatform)
---

Add KDateTime

---

README.md

* KMP Crypto Datatypes & ASN.1 Parser+Encoder
[Library Link](https://github.com/a-sit-plus/kmp-crypto)
---

Add KMP-Crypto

---

README.md

* Wrapper of `kotlin.Result` with KMM goodness to make it usable as part of XCFrameworks.
[Library Link](https://github.com/a-sit-plus/KmmResult)
---

Add KmmResult

---

README.md

* This library implements verifiable credentials to support several use cases, i.e. issuing of credentials, presentation of credentials and validation thereof. This library may be shared between backend services issuing credentials, wallet apps holding credentials, and verifier apps validating them.  
Credentials may be represented in the [W3C VC Data Model](https://w3c.github.io/vc-data-model/) or as mobile driving licences from [ISO/IEC 18013-5:2021](https://www.iso.org/standard/69084.html). Issuing may happen according to [ARIES RFC 0453 Issue Credential V2](https://github.com/hyperledger/aries-rfcs/tree/main/features/0453-issue-credential-v2) or with [OpenID for Verifiable Credential Issuance](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html). Presentation of …

Add VC Library

---

README.md

* The repository has been archived by the owner on Jul 8, 2022  and now it is now read-only. It is no longer recommended to use in new projects.
[Library Link](https://github.com/korlibs-archive/klock)
---

docs: Remove Klock from README.md

---

README.md

* Kotlin Object Multiplatform Mapper which generates mapping function via KSP and supports multi-mapping, converters, resolvers, null-substitute etc.
[KOMM](https://github.com/Scogun/komm)
* Easy-to-use lightweight library which adds configurable output cache support to [Ktor](https://github.com/ktorio/ktor), including [Memory](https://github.com/Scogun/ktor-simple-cache/tree/main/ktor-simple-memory-cache) and [Redis](https://github.com/Scogun/ktor-simple-cache/tree/main/ktor-simple-redis-cache) providers.
[ktor-simple-cache](https://github.com/Scogun/ktor-simple-cache)
---

Add new KMP libraries, update badges

---

README.md

* Ksoup is a Kotlin Multiplatform library for working with HTML and XML.
[Library Link](https://github.com/fleeksoft/ksoup)
---

add target badges for ksoup

---

README.md

* Kotlin multiplatform Bluesky/ATProtocol library.
[kbsky](https://github.com/uakihir0/kbsky)
---

add kbsky.

---

README.md

* Multibase and UVarInt implementation
[Library Link](https://github.com/a-sit-plus/multibase)
---

Add multibase

---

README.md

Closes https://github.com/AAkira/Kotlin-Multiplatform-Libraries/issues/227 
---
This PR fixes the broken badge reference of [kotlinx-murmurhash](https://github.com/goncalossilva/kotlinx-murmurhash) 
```diff
- ![badge][badge-macos] 
+ ![badge][badge-mac]
```

Fix invalid badge reference
