README.md
=> Add missing platform

README.md
This package provides APIs for common use cases to interact with the file system on iOS and Android.
Highlights
- Cross platform Thread-Safe API to read/write/copy/move and manage files on both iOS and Android
- Support for UTF-8, Ascii and Base64 formats while reading and writing.
Link to docs
https://suparngp.github.io/kotlin-multiplatform-projects/fs/docs/suparnatural-fs/index.html
Link to source
https://github.com/suparngp/kotlin-multiplatform-projects/tree/master/fs
Link to License (MIT)
https://github.com/suparngp/kotlin-multiplatform-projects/blob/master/LICENSE
Link to artifacts (Bintray)
https://dl.bintray.com/suparnatural/kotlin-multiplatform/suparnatural-kotlin-multiplatform/
=> suparnatural-fs

README.md
This package provides unified APIs for multithreading and concurrency on iOS and Android for KMP projects.
Highlights
- Cross Platform Worker API which takes care of properly sharing objects across threads.
- Resumable Jobs which can start on one thread but continue on another without state transfer issues
- Various Lock and Datastructure Implementations
Link to docs
https://suparngp.github.io/kotlin-multiplatform-projects/concurrency/docs/suparnatural-concurrency/index.html
Link to source
https://github.com/suparngp/kotlin-multiplatform-projects/tree/master/concurrency
Link to License (MIT)
https://github.com/suparngp/kotlin-multiplatform-projects/blob/master/LICENSE
Link to artifacts (Bintray)
https://dl.bintray.com/suparnatural/kotlin-multiplatform/suparnatural-kotlin-multiplatform/
=> suparnatural-concurrency

README.md
Add the okio.
This is a file I/O library.
But it is WIP.
https://github.com/square/okio/blob/master/CHANGELOG.md#version-230
=> Add the okio.

README.md
A high speed thread safe in-memory cache with persistence.
Highlights
In-Memory Cache with LinearProbing and Robin hood Hashing support. You can choose any.
Different Cache Replacement Policies support (FIFO)
Thread Safety on both iOS and Android with any readers/one writer.
Backed by Blocking/Non-Blocking Disk storage for persistence and reloading the cache after cold start.
A pluggable interface to define custom cache replacement policies and persistent stores.
Link to docs
https://suparngp.github.io/kotlin-multiplatform-projects/cache/docs/suparnatural-cache/index.html
Link to source
https://github.com/suparngp/kotlin-multiplatform-projects/tree/master/cache
Link to License (MIT)
https://github.com/suparngp/kotlin-multiplatform-projects/blob/master/LICENSE
Link to artifacts (Bintray) …
=> suparnatural-cache

README.md
added libs in architecture section, project template and gradle plugin
=> append some moko libraries into the list

README.md
Adds multiplatform paging for Android and iOS
=> Adds multiplatform paging

README.md
Adds Ktor Client OAuth Feature for automatically injecting tokens as headers and handling refreshes on `401 Unauthorized` calls
=> Adds Ktor Client OAuth Feature

Contributing.md, README.md
I modified the platform badges.
close #20
=> Refactoring

README.md
Add the [official Firebase SDK](https://firebaseopensource.com/projects/gitliveapp/firebase-kotlin-sdk/).
=> Add official Firebase SDK

README.md
I've listed kotest twice because it has two major components - the test engine, and the assertions library, and you can use either without the other, and one is more multiplatform than the other.
=> Added Kotest

README.md
The [Measured](https://github.com/nacular/measured) library provides a very simple and intuitive way to deal with all kinds of units of measures. Good examples are handling time durations, or binary sizes.
```kotlin
val velocity     = 5 * meters / seconds
val acceleration = 9 * meters / (seconds * seconds)
val time         = 1 * minutes
//  d = vt + ½at²
val distance     = velocity * time + 1.0/2 * acceleration * time * time
println(distance                ) // 16500 m
println(distance `as` kilometers) // 16.5 km
println(distance `as` miles     ) // 10.25262467191601 mi
println(5 * miles / hours `as` meters / seconds) // 2.2352 m/s
```
=> Add Measured

README.md
=> Change Library name and url

README.md
Sorry, I had to fix next line issue
=> Moved badges to next line for kcron

README.md
Adding PopKorn. A kotlin multiplatform dependency injector that works without writing any extra file (no modules or components)
=> Add PopKorn DI

README.md
add [kotlin-result](https://github.com/michaelbull/kotlin-result) library.
At its core it provides a Result monad for modelling success or failure operations. 
It provides numerous useful functions for operating over this result type, drawing inspiration from other functional languages such as scala and haskell.
Something that sets it apart from other libs (apart from Arrow) is it includes an implementation of monad comprehensions that also works with coroutines.
=> Add kotlin-result

README.md
https://github.com/Animeshz/keyboard-mouse-kt
It helps to catch and send global keyboard events (and will mouse events in future as well) and states, also provides high-level abstraction to easily interact with them.
=> Add keyboard-mouse-kt

README.md
Also add watchos and tvos badges to kotlin-multiplatform-bignum library
=> Add kotlin multiplatform libsodium library

README.md
**Kermit** - https://github.com/touchlab/Kermit
=> Add Kermit Logging Library

README.md
KMMT is a KMM based project template designed to simplify the KMM development. It uses a simplified MVVM approach that can be shared both in android and iOS easily.
=> Add KMMT : Kotlin Multiplatform Mobile Template

README.md
=> Add nodejs badge.

README.md
Now the storage has native impl for android with `SharePreferences`, so I added the bage
=> New platforms for `kds`

README.md
Flywheel - https://github.com/abhimuktheeswarar/Flywheel
=> Add Flywheel

README.md
FLowExt - https://github.com/hoc081098/FlowExt
=> Add `FlowExt`

README.md
A library to use Kotlin Coroutines from Swift code in KMP apps:
https://github.com/rickclephas/KMP-NativeCoroutines
=> Add KMP-NativeCoroutines

README.md
Hello!
Could you add another log lib to the list?
https://github.com/september669/KmmAnkoLogger
=> Add KmmAnkoLogger

README.md
Adds my [SemVer-KMP](https://github.com/QazCetelic/SemVer-KMP) library.
=> Add SemVer-KMP

README.md
Orbit is a great MVI framework. Authors detail [here](https://appmattus.medium.com/top-android-mvi-libraries-in-2021-de1afe890f27) why it's from the best.
=> Add Orb MVI

README.md
Hey! 
In this PR I have added [kotlin-semver](https://github.com/z4kn4fein/kotlin-semver) to the library collection.
Thanks!
=> Add kotlin-semver

README.md
Apologies @AAkira, I named it "Orb" instead of it "Orbit". I was maybe thinking of my old [company](https://imagine-orb.com). 😅
=> Update Orb -> Orbit

README.md
[MocKMP](https://github.com/Kodein-Framework/MocKMP)
MocKMP is a Kotlin/Multiplatform Kotlin Symbol Processor that generates mocks for interfaces and faking for concrete trees to be used in testing.
=> add MocKMP to testing section

README.md
* A Kotlin multiplatform library for building dynamic server-driven UI
Docs is here.  
https://www.componentbox.io/
[Library Link](https://github.com/dropbox/componentbox)
---
=> Add component box.

README.md
Fix https://github.com/AAkira/Kotlin-Multiplatform-Libraries/pull/103#discussion_r867410700
=> Fix title of multiplatform-viewmodel

README.md
* KMMT is a Multi-Module KMM based project template designed to simplify the KMM development. It uses a simplified approach that can be shared both in android and iOS easily. This template include network module, persistence module, resource module, analytics module ( with ios native library integration), domain module, presenter module etc.
[Library Link](https://github.com/jittya/KMMT)
---
=> KMMT moved to project template section

README.md
For Base64 and Hex string encoding / decoding.
---
=> Add Kase64 and Kex libraries

README.md
* Opinionated Application State Management framework for Kotlin Multiplatform
[Library Link](https://github.com/copper-leaf/ballast)
=> Add Ballast KMM MVI Library

README.md
* Door is a Kotlin Symbol Processor that provides Kotlin Multiplatform support for Room databases. It currently supports SQLite and Postgres on JVM (via JDBC), and SQLite (via SQL.js) on JS (browser). Door generates expect/actual classes. The implementation on Android is Room itself. Normal queries, suspended queries, Kotlin Flow, LiveData, and paging are all supported.
[Library Link](https://www.github.com/UstadMobile/door)
---
- [ x ] Confirmed that two spaces were added at the end of the description to break a new line.
=> Add door database

README.md
* A tiny Kotlin multiplatform library that assists in saving and restoring objects to and from disk using kotlinx.coroutines, kotlinx.serialisation and okio
[KStore](https://github.com/xxfast/KStore)
---
=> Add KStore

README.md
Kottage is a Multiplatform KVS Store
=> Add Kottage

README.md
* A Kotlin Multiplatform library for creating a debugging menu
[Library Link](https://github.com/chopyourbrain/kontrol)
---
=> Add Kontrol

README.md
Reflects its project description in its repository
=> Updated okio's description

README.md
Mordant provides useful widgets for CLI applications. It also provides an intuitive DSL to render tables.
* Multiplatform text styling for Kotlin command-line applications
[Library Link](https://github.com/ajalt/mordant)
---
=> Add Mordant

README.md
A Library to perform json rpc requests
https://github.com/Reedyuk/jsonrpc-kotlin-client
---
=> Added json rpc client

README.md
* Kotlin Multiplatform File System Watcher
https://github.com/irgaly/kfswatch
---
=> Add Kfswatch

README.md
* Update targets
[kotlin-inject](https://github.com/evant/kotlin-inject) - Dependency injection lib for kotlin.
[Koject](https://github.com/mori-atsushi/koject) - DI Container library for Kotlin Multiplatform.
---
=> Update the di section

README.md
* Assertions for kotlin inspired by assertj.
[Library Link](https://github.com/willowtreeapps/assertk)
---
=> Add assertk

README.md
* Y—Chat is a Kotlin Multiplatform (KMP) project that provides a simple API for integrating the powerful ChatGPT language model developed by OpenAI into mobile applications running on multi platforms.
[Library Link](https://github.com/yml-org/ychat)
---
=> Add Y-Chat

README.md
* Library description (If you want to write)
[Library Link]()
---
=> Koala plot

README.md
* Kotlin Symbol Processor to simplify analytics tracking.
[trckr](https://github.com/dzmpr/trckr)
---
=> Add trckr KSP processor

README.md
Simple, powerful and lightweight Kotlin Multiplatform Network Client
[kotliny.network](https://github.com/corbella83/kotliny.network)
---
=> Add kotliny.network

README.md
A couple of libraries written by me.
=> Add Kronos & MaterialThemePrefs

README.md
Kotlin Flow caching and request sharing. Main idea: don't request data more times than it's needed.
https://github.com/Andrew0000/Universal-Cache  
---
=> Add Universal-Cache

README.md
* Kotlin Multiplatform syntax highlighting engine.
[Highlights](https://github.com/SnipMeDev/Highlights)
---
=> Add Highlights

README.md
Library Links: https://github.com/respawn-app/FlowMVI
https://github.com/respawn-app/ApiResult
---
=> Added FlowMVI and ApiResult

README.md
*A Compose-multiplatform navigation library that leverage Decompose to create an API inspired by Conductor
[Library Link](https://github.com/xxfast/Decompose-Router)
---
=> Add decompose router

README.md
=> Fixes link to Korim

README.md
* Kotlin Multiplatform syntax highlighting engine.  
[KodeView](https://github.com/SnipMeDev/Highlights)
---
=> Add KodeView

README.md
* A lightweight framework that includes a set of architecture tools and approaches for building scalable, fully multiplatform applications (100% shared logic). Streamlines project modularization through the separation into independent parts and provides features like lifecycle-aware components, declarative navigation, and constructor-based DI.
[Library Link](https://github.com/trueangle/Blackbox)
---
=> Added Blackbox

README.md
* KCrypt is a Kotlin Multiplatform Mobile (KMM) library that provides a secure and unified way to manage encryption keys across iOS and Android platforms. It abstracts the complexities of key generation, encryption, and storage, thereby providing you with a unique key that can be used for cryptographic purposes, allowing you to focus on building secure and robust multiplatform applications.
* Kcrypt also provides a secured storage where in key-value pairs.
[KCrypt](https://github.com/abhriyaroy/KCrypt)
---
=> Add library KCrypt inside KVS

README.md
[Sekret](https://github.com/DatL4g/Sekret)
---
=> Added Sekret

README.md
* Multik is the Kotlin multiplatform library for mathematical computations on multidimensional arrays (ndarrays).
[Multik](https://github.com/Kotlin/multik)
---
=> Add multik

README.md
* Compose Multiplatform animation library that parses Adobe After Effects animations. Inspired by Lottie from Airbnb.  
[Kottie](https://github.com/ismai117/kottie)
---
=> Kottie library added

README.md
* VisualFSM is a Kotlin Multiplatform library for implements an FSM-based (Finite-state machine) MVI pattern and a set of tools for visualization and analysis of FSM's diagram of states. 
[VisualFSM](https://github.com/Kontur-Mobile/VisualFSM)
---
=> Add VisualFSM

README.md
* 3D graphics engine for Kotlin Multiplatform
[Library Link](https://github.com/zakgof/korender)
---
=> Add Korender

README.md
Updates names, links and descriptions of A-SIT Plus libraries to reflect rebranding:
* KMM VC Library -> VC-K
* KMP-Crypto -> Signum
* JsonPath -> JsonPath4K
No new Libraries were added.
=> Update ASP Libs

README.md
https://github.com/Ivy-Apps/di
---
=> Add Ivy DI

README.md
A multiplatform library (currently supporting iOS, Android & AppleWatch). Soon to support other platforms too.
Currently at 182 stars
Contains 40+ modules for everything a project could need, from InAppReviews, Local Notifications, taking Photos/Videos and Biometric Authentication.
[Library Link](https://github.com/TheArchitect123/KmpEssentials)
=> KmpEssentials (222 Stars), Architecture Component
